// Re-export all shared types for use in the client
export type {
  GameState,
  Player,
  BoardSpace,
  SpaceType,
  Bank,
  Card,
  CardAction,
  Auction,
  Trade,
  TradeOffer,
  JoinGamePayload,
  StartGamePayload,
  RollDicePayload,
  BuyPropertyPayload,
  DeclineBuyPayload,
  PlaceBidPayload,
  WithdrawFromAuctionPayload,
  BuildHousePayload,
  BuildHotelPayload,
  SellHousePayload,
  SellHotelPayload,
  MortgagePropertyPayload,
  UnmortgagePropertyPayload,
  ProposeTradePayload,
  RespondTradePayload,
  PayJailFinePayload,
  UseJailCardPayload,
  DeclareBankruptcyPayload,
  EndTurnPayload,
  LeaveGamePayload,
} from '../../../shared/types';
